### ISSUE TITLE
Crash when user press back button in ActivityPLayer

### ISSUE THREAD

**Issue by MrLukashem** [MrLukashem/AndroidAudioPlayer#4]
When user don't start playback and then press back button a crash occurs.

**Comment by MrLukashem** [comment]
It occurs because we invoke cancel( ) on timer when it is not initialized yet.
Timer is not initialized because play button hasn't been pressed.

`02-01 16:14:42.341 29263-29263/com.player.mrlukashem.customplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.player.mrlukashem.customplayer, PID: 29263
                                                                                    java.lang.RuntimeException: Unable to stop activity {com.player.mrlukashem.customplayer/com.player.mrlukashem.customplayer.player.PlayerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.CountDownTimer.cancel()' on a null object reference
                                                                                        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5021)
                                                                                        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5089)
                                                                                        at android.app.ActivityThread.access$1700(ActivityThread.java:222)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1854)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:158)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.CountDownTimer.cancel()' on a null object reference
                                                                                        at com.player.mrlukashem.customplayer.player.PlayerActivity.releaseResources(PlayerActivity.java:153)
                                                                                        at com.player.mrlukashem.customplayer.player.PlayerActivity.onStop(PlayerActivity.java:264)
                                                                                        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1306)
                                                                                        at android.app.Activity.performStop(Activity.java:7070)
                                                                                        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5016)
                                                                                        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5089) 
                                                                                        at android.app.ActivityThread.access$1700(ActivityThread.java:222) 
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1854) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                        at android.os.Looper.loop(Looper.java:158) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) `
